swagger: '2.0'
definitions:
  Error:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
    required:
      - code
      - message
x-components:
  parameters:
    cursor:
      description: An opaque identifier that points to the next item in the collection.
      in: query
      name: cursor
      x-example: 01BX9NSMKVXXS5PSP2FATZM123
      type: string
    limit:
      description: How many items to return at one time (max 100)
      in: query
      name: limit
      format: int32
      type: integer
    offset:
      description: The zero-ary offset index into the results
      in: query
      name: offset
      default: 0
      format: int32
      type: integer
    sort:
      description: Sorting order
      in: query
      name: sort
      default: 0
      x-example: +name
      type: string
  responses:
    400BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Bad Request
    404NotFound:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Not Found
    429TooManyRequests:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Too many requests
    503ServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Service Unavailable
    default:
      content:
        application/json:
          schema:
            $ref: '#/definitions/Error'
      description: Unexpected error
  headers:
    X-Rate-Limit-Limit:
      description: The number of allowed requests in the current period
      type: integer
    X-Rate-Limit-Remaining:
      description: The number of remaining requests in the current period
      type: integer
    X-Rate-Limit-Reset:
      description: The number of seconds left in the current period
      type: integer
